# Generated by Django 3.1.7 on 2024-11-15 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_auto_20241110_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.CharField(blank=True, default='15 November 2024', max_length=100),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
